spring.datasource.url=jdbc:postgresql://db:5432/test
spring.datasource.username=taskuser
spring.datasource.password=taskpass
spring.jpa.open-in-view=false
jwt.secret="mySecretKeymySecretKeymySecretKey123"

server.port=8080