spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=111
spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false

server.port=8080